### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [Mavrin/remark-typograf#2]
Hi!

remark is switching to a new parser internally ([`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)).
It seems this plugin should be fine, however, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by Mavrin** [comment]
Looks all work good. Only [one test](https://github.com/Mavrin/remark-typograf/runs/1206384258#step:6:34)  is not passed.
```
expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    - ## 1. Это сложно :(.
    + ## 1\. Это сложно :(.
```
Maybe, I should set some option for remark-strigify? Any suggestions?

**Comment by wooorm** [comment]
We are now escaping more content that could accidentally turn into markdown. Here, the escape is to prevent the text from turning into a list. The escape does not harm, so you might as well change it in the fixture.

On the other hand, flow constructs (lists, block quotes, definitions, etc) can’t exist in ATX headings, so I’ll look into not adding that escape!

**Comment by Mavrin** [comment]
Thank you!
I think we can close this issue.
